### ISSUE TITLE
FluentServer not decoding protocol correctly?

### ISSUE THREAD

**Issue by ForbiddenEra** [fluent/fluent-logger-forward-node#37]
Hi,

Trying to use this as a server/sink to have fluent forward logs into a node app, but nothing seems to get emitted when forwarded in by an actual fluentd..

Using this test code:
```
#!/usr/bin/node
'use strict';

const FluentServer = require("@fluent-org/logger").FluentServer;
const FluentClient = require("@fluent-org/logger").FluentClient;

const server = new FluentServer({ listenOptions: { port: 24420 }});

const logger = new FluentClient("tag_prefix", {
  socket: {
    host: "localhost",
    port: 24420,
    timeout: 3000, // 3 seconds
  }
});


let main = async ()=>{
        await server.listen();
        logger.emit('tag', { message: 'message' });
};

server.on('entry', (a,b,c) => console.log(a,b,c));

main()
```

I do immediately see the message forwarded into itself with this test app, however I see nothing emitted when my local fluentd connects and flushes it's buffer.

I've tried the config posted in the readme basically; I have my local syslog as a source tagged as system.

```
<match system.**>
  @type forward
  send_timeout 60s
  recover_wait 10s
  hard_timeout 60s

  <server>
    name fluent_node 
    host 127.0.0.1
    port 24420
    weight 60
  </server>

  <secondary>
    @type file
    path /var/log/calyptia-fluentd/forward-failed
  </secondary>
</match>
```

I've also tried <match **> for all messages.. I do not ever see a forward-failed file. The fluentd log complains when my node app isn't listening and then shows that it flushed when it does start listening.

I've setup a copy output to copy to the forward for the node sink and to a local file and can indeed see the log entries in the local file.

```
2022-05-17 12:16:49 +0000 [warn]: #0 recovered forwarding server 'fluent_node' host="127.0.0.1" port=24420
2022-05-17 12:16:55 +0000 [warn]: #0 retry succeeded. chunk_id="5df3416a0841558c7b24a18a52894e0e"
2022-05-17 12:18:16 +0000 [warn]: #0 failed to flush the buffer. retry_times=0 next_retry_time=2022-05-17 12:18:18 +0000 chunk="5df341e996491df677197139862f6aa5" error_class=Errno::ECONNREFUSED error="Connection refused - connect(2) for \"127.0.0.1\" port 24420"
  2022-05-17 12:18:16 +0000 [warn]: #0 /opt/calyptia-fluentd/lib/ruby/gems/3.0.0/gems/fluentd-1.14.6/lib/fluent/plugin_helper/socket.rb:62:in `initialize'
  2022-05-17 12:18:16 +0000 [warn]: #0 /opt/calyptia-fluentd/lib/ruby/gems/3.0.0/gems/fluentd-1.14.6/lib/fluent/plugin_helper/socket.rb:62:in `new'
  2022-05-17 12:18:16 +0000 [warn]: #0 /opt/calyptia-fluentd/lib/ruby/gems/3.0.0/gems/fluentd-1.14.6/lib/fluent/plugin_helper/socket.rb:62:in `socket_create_tcp'
  2022-05-17 12:18:16 +0000 [warn]: #0 /opt/calyptia-fluentd/lib/ruby/gems/3.0.0/gems/fluentd-1.14.6/lib/fluent/plugin/out_forward.rb:410:in `create_transfer_socket'
  2022-05-17 12:18:16 +0000 [warn]: #0 /opt/calyptia-fluentd/lib/ruby/gems/3.0.0/gems/fluentd-1.14.6/lib/fluent/plugin/out_forward/connection_manager.rb:46:in `call'
  2022-05-17 12:18:16 +0000 [warn]: #0 /opt/calyptia-fluentd/lib/ruby/gems/3.0.0/gems/fluentd-1.14.6/lib/fluent/plugin/out_forward/connection_manager.rb:46:in `connect'
  2022-05-17 12:18:16 +0000 [warn]: #0 /opt/calyptia-fluentd/lib/ruby/gems/3.0.0/gems/fluentd-1.14.6/lib/fluent/plugin/out_forward.rb:807:in `connect'
  2022-05-17 12:18:16 +0000 [warn]: #0 /opt/calyptia-fluentd/lib/ruby/gems/3.0.0/gems/fluentd-1.14.6/lib/fluent/plugin/out_forward.rb:676:in `send_data'
  2022-05-17 12:18:16 +0000 [warn]: #0 /opt/calyptia-fluentd/lib/ruby/gems/3.0.0/gems/fluentd-1.14.6/lib/fluent/plugin/out_forward.rb:365:in `block in write'
  2022-05-17 12:18:16 +0000 [warn]: #0 /opt/calyptia-fluentd/lib/ruby/gems/3.0.0/gems/fluentd-1.14.6/lib/fluent/plugin/out_forward/load_balancer.rb:46:in `block in select_healthy_node'
  2022-05-17 12:18:16 +0000 [warn]: #0 /opt/calyptia-fluentd/lib/ruby/gems/3.0.0/gems/fluentd-1.14.6/lib/fluent/plugin/out_forward/load_balancer.rb:37:in `times'
  2022-05-17 12:18:16 +0000 [warn]: #0 /opt/calyptia-fluentd/lib/ruby/gems/3.0.0/gems/fluentd-1.14.6/lib/fluent/plugin/out_forward/load_balancer.rb:37:in `select_healthy_node'
  2022-05-17 12:18:16 +0000 [warn]: #0 /opt/calyptia-fluentd/lib/ruby/gems/3.0.0/gems/fluentd-1.14.6/lib/fluent/plugin_helper/service_discovery/manager.rb:108:in `select_service'
  2022-05-17 12:18:16 +0000 [warn]: #0 /opt/calyptia-fluentd/lib/ruby/gems/3.0.0/gems/fluentd-1.14.6/lib/fluent/plugin_helper/service_discovery.rb:82:in `service_discovery_select_service'
  2022-05-17 12:18:16 +0000 [warn]: #0 /opt/calyptia-fluentd/lib/ruby/gems/3.0.0/gems/fluentd-1.14.6/lib/fluent/plugin/out_forward.rb:365:in `write'
  2022-05-17 12:18:16 +0000 [warn]: #0 /opt/calyptia-fluentd/lib/ruby/gems/3.0.0/gems/fluentd-1.14.6/lib/fluent/plugin/output.rb:1179:in `try_flush'
  2022-05-17 12:18:16 +0000 [warn]: #0 /opt/calyptia-fluentd/lib/ruby/gems/3.0.0/gems/fluentd-1.14.6/lib/fluent/plugin/out_forward.rb:353:in `try_flush'
  2022-05-17 12:18:16 +0000 [warn]: #0 /opt/calyptia-fluentd/lib/ruby/gems/3.0.0/gems/fluentd-1.14.6/lib/fluent/plugin/output.rb:1500:in `flush_thread_run'
  2022-05-17 12:18:16 +0000 [warn]: #0 /opt/calyptia-fluentd/lib/ruby/gems/3.0.0/gems/fluentd-1.14.6/lib/fluent/plugin/output.rb:499:in `block (2 levels) in start'
  2022-05-17 12:18:16 +0000 [warn]: #0 /opt/calyptia-fluentd/lib/ruby/gems/3.0.0/gems/fluentd-1.14.6/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2022-05-17 12:18:17 +0000 [warn]: #0 failed to flush the buffer. retry_times=1 next_retry_time=2022-05-17 12:18:20 +0000 chunk="5df341e996491df677197139862f6aa5" error_class=Errno::ECONNREFUSED error="Connection refused - connect(2) for \"127.0.0.1\" port 24420"
  2022-05-17 12:18:17 +0000 [warn]: #0 suppressed same stacktrace
2022-05-17 12:18:19 +0000 [warn]: #0 failed to flush the buffer. retry_times=2 next_retry_time=2022-05-17 12:18:24 +0000 chunk="5df341e996491df677197139862f6aa5" error_class=Errno::ECONNREFUSED error="Connection refused - connect(2) for \"127.0.0.1\" port 24420"
  2022-05-17 12:18:19 +0000 [warn]: #0 suppressed same stacktrace
2022-05-17 12:18:23 +0000 [warn]: #0 failed to flush the buffer. retry_times=3 next_retry_time=2022-05-17 12:18:32 +0000 chunk="5df341e996491df677197139862f6aa5" error_class=Errno::ECONNREFUSED error="Connection refused - connect(2) for \"127.0.0.1\" port 24420"
  2022-05-17 12:18:23 +0000 [warn]: #0 suppressed same stacktrace
2022-05-17 12:18:32 +0000 [warn]: #0 failed to flush the buffer. retry_times=4 next_retry_time=2022-05-17 12:18:49 +0000 chunk="5df341e996491df677197139862f6aa5" error_class=Errno::ECONNREFUSED error="Connection refused - connect(2) for \"127.0.0.1\" port 24420"
  2022-05-17 12:18:32 +0000 [warn]: #0 suppressed same stacktrace
2022-05-17 12:18:47 +0000 [warn]: #0 detached forwarding server 'fluent_node' host="127.0.0.1" port=24420 phi=16.00192534264217 phi_threshold=16
2022-05-17 12:18:48 +0000 [warn]: #0 failed to flush the buffer. retry_times=5 next_retry_time=2022-05-17 12:19:21 +0000 chunk="5df341e996491df677197139862f6aa5" error_class=Fluent::Plugin::ForwardOutput::NoNodesAvailable error="no nodes are available"
  2022-05-17 12:18:48 +0000 [warn]: #0 /opt/calyptia-fluentd/lib/ruby/gems/3.0.0/gems/fluentd-1.14.6/lib/fluent/plugin/out_forward/load_balancer.rb:55:in `select_healthy_node'
  2022-05-17 12:18:48 +0000 [warn]: #0 /opt/calyptia-fluentd/lib/ruby/gems/3.0.0/gems/fluentd-1.14.6/lib/fluent/plugin_helper/service_discovery/manager.rb:108:in `select_service'
  2022-05-17 12:18:48 +0000 [warn]: #0 /opt/calyptia-fluentd/lib/ruby/gems/3.0.0/gems/fluentd-1.14.6/lib/fluent/plugin_helper/service_discovery.rb:82:in `service_discovery_select_service'
  2022-05-17 12:18:48 +0000 [warn]: #0 /opt/calyptia-fluentd/lib/ruby/gems/3.0.0/gems/fluentd-1.14.6/lib/fluent/plugin/out_forward.rb:365:in `write'
  2022-05-17 12:18:48 +0000 [warn]: #0 /opt/calyptia-fluentd/lib/ruby/gems/3.0.0/gems/fluentd-1.14.6/lib/fluent/plugin/output.rb:1179:in `try_flush'
  2022-05-17 12:18:48 +0000 [warn]: #0 /opt/calyptia-fluentd/lib/ruby/gems/3.0.0/gems/fluentd-1.14.6/lib/fluent/plugin/out_forward.rb:353:in `try_flush'
  2022-05-17 12:18:48 +0000 [warn]: #0 /opt/calyptia-fluentd/lib/ruby/gems/3.0.0/gems/fluentd-1.14.6/lib/fluent/plugin/output.rb:1500:in `flush_thread_run'
  2022-05-17 12:18:48 +0000 [warn]: #0 /opt/calyptia-fluentd/lib/ruby/gems/3.0.0/gems/fluentd-1.14.6/lib/fluent/plugin/output.rb:499:in `block (2 levels) in start'
  2022-05-17 12:18:48 +0000 [warn]: #0 /opt/calyptia-fluentd/lib/ruby/gems/3.0.0/gems/fluentd-1.14.6/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2022-05-17 12:19:21 +0000 [warn]: #0 failed to flush the buffer. retry_times=6 next_retry_time=2022-05-17 12:20:22 +0000 chunk="5df341e996491df677197139862f6aa5" error_class=Fluent::Plugin::ForwardOutput::NoNodesAvailable error="no nodes are available"
  2022-05-17 12:19:21 +0000 [warn]: #0 suppressed same stacktrace
2022-05-17 12:19:26 +0000 [warn]: #0 recovered forwarding server 'fluent_node' host="127.0.0.1" port=24420
2022-05-17 12:20:17 +0000 [warn]: #0 detached forwarding server 'fluent_node' host="127.0.0.1" port=24420 phi=16.068666338465153 phi_threshold=16
2022-05-17 12:20:22 +0000 [warn]: #0 failed to flush the buffer. retry_times=7 next_retry_time=2022-05-17 12:22:36 +0000 chunk="5df341e996491df677197139862f6aa5" error_class=Fluent::Plugin::ForwardOutput::NoNodesAvailable error="no nodes are available"
  2022-05-17 12:20:22 +0000 [warn]: #0 suppressed same stacktrace
2022-05-17 12:22:36 +0000 [warn]: #0 failed to flush the buffer. retry_times=8 next_retry_time=2022-05-17 12:26:35 +0000 chunk="5df341e996491df677197139862f6aa5" error_class=Fluent::Plugin::ForwardOutput::NoNodesAvailable error="no nodes are available"
  2022-05-17 12:22:36 +0000 [warn]: #0 suppressed same stacktrace
2022-05-17 12:24:47 +0000 [warn]: #0 recovered forwarding server 'fluent_node' host="127.0.0.1" port=24420
2022-05-17 12:26:35 +0000 [warn]: #0 retry succeeded. chunk_id="5df341e996491df677197139862f6aa5"
```

Perhaps I'm reading it wrong but retry succeeded with a chunk id sounds like it's definitely pushing a chunk but I'm not getting any event emitted while I do when I push it locally from node.

Any ideas what my issue might be? is there a possible version issue or something?

thanks

**Comment by ForbiddenEra** [comment]
Tried different versions of fluent-logger, msgpack.. not sure whats going on.. the extensionCodec never gets called, decodeMultiAsync does see the 2nd one in binary but decodes diff?

Tried td-agent v3 as well.. I know I must be missing something but I can't seem to figure out what it is..

![image](https://user-images.githubusercontent.com/7980490/169302859-1e8eaa57-bed3-4263-a1fe-6a987d4b3d6e.png)

**Comment by ForbiddenEra** [comment]
On the protocol specification for fluentd, I noticed something that could maybe affect this..

https://github.com/fluent/fluentd/wiki/Forward-Protocol-Specification-v1

Under "PacketForward Mode":
> Note: out_forward plugin sends events by the PackedForward mode. It encloses event records with msgpack str format instead of bin format for a backward compatibility reason.

It seems odd that this would be the issue as I'm basically using the config listed in the docs as shown above and even so, wouldn't the lib need to be able to parse both anyhow..? If this is the issue, then is it possible the listed config / server never worked with forwarding from actual fluentd..? Again, seems odd that there would be posted config for fluentd for forwarding to the node FluentServer if it wasn't ever working..?

Node version..? Dependency version..? fluentd version..?

Currently on Node v17.9.0; @fluent-org/logger v1.0.8, @msgpack/msgpack ^2.7.1 (as specified by @fluent-org/logger)

:'(

**Comment by ForbiddenEra** [comment]
So looking even closer, it seems like some of the bytes are slightly diff..?

The only thing I can think now is the extensionCodec isn't working to decode the time and causing it to sort of garbage..?

But I need a D4-D8 or C7-C9 to get decodeExtension to fire? I'm getting DB?

I've referred the protocol docs for fluentd and msgpack..? :'(

![image](https://user-images.githubusercontent.com/7980490/169328712-43b3c6b7-3a35-4c8b-b72f-6a715163bb25.png)

**Comment by jamiees2** [comment]
I'm going to need to dig deeper on this, thanks for the detailed bug report! To be honest I tested this configuration against Fluent Bit, and assumed that Fluentd would work the same, but it doesn't :( It should though, I'll dig into why that is. 

It looks like it's not parsing it correctly at the msgpack level, but I did figure out where the 0xDB is coming from - see https://github.com/fluent/fluentd/blob/master/lib/fluent/plugin/out_forward.rb#L665

**Comment by ForbiddenEra** [comment]
hm - I wonder if that's related to one of my last posts, where the docs say that out_foward uses string not binary for something? at least, that's sort of what he comment there implies:

```
        # https://github.com/fluent/fluentd/wiki/Forward-Protocol-Specification-v1#packedforward-mode
        # out_forward always uses str32 type for entries.
```

I wasn't sure if the note in the docs meant just the section of the record, the whole forward entry or what; this:

``
Note: out_forward plugin sends events by the PackedForward mode. It encloses event records with msgpack str format instead of bin format for a backward compatibility reason.
``

from https://github.com/fluent/fluentd/wiki/Forward-Protocol-Specification-v1#packedforward-mode

In the msgpack spec, 0xdb shows as a 32b/4B string, right? And it seems like indeed it's getting decoded AS that..? right after 0xdb we see decodeUtf8String 98 4 (98 is from 'headerByte' and 4 is the length)

But; the data is clearly NOT a utf8 string.......is this actually, technically, a bug in fluentd vs the msgpack spec?!

Because that almost seems like the case here..? I'm about to head out so haven't looked deeply but thanks for finding where that comes from; not a huge ruby person but can probably at least read it :)

Does seem a little interesting that Bit & fluentd would be different; I almost tempted with bit instead as I'm setting up a new architecture here but thought I might need some extra features of fluentd itself; I'm still new to fluentd itself hence me not being sure about whether I was just having a misconfiguration issue, but seems like this goes deeper.

Thanks for getting back & looking into it, hope your con was great!

**Comment by ForbiddenEra** [comment]
``entries = [0xdb, chunk_io.size].pack('CN')``

So I am guessing this is packing 0xdb byte along with the size but not sure about the CN?

Tbh I'm not even sure where it gets the actual entry here I only see db and size but again I don't really do ruby lol trying to figure this out on my phone while out and about

**Comment by ForbiddenEra** [comment]
So, it seems you are correct about fluent-bit.

I setup a docker fluent-bit instance that simply has a forward input from fluentd and a foward output to my test app, and that seems to work correctly.

![image](https://user-images.githubusercontent.com/7980490/169687494-8208809d-d78b-4dc3-969a-040ac40ee773.png)

**Comment by ForbiddenEra** [comment]
So the tail events that are getting fowarded but not fired are actually passing through the extensionCodec properly and getting decoded (when forwaded through flluent-bit)

![image](https://user-images.githubusercontent.com/7980490/169688800-02bcb658-ce91-4b79-875b-4e01cf783034.png)

**Comment by ForbiddenEra** [comment]
So it really just seems like the content of the actual messages which should be packed isn't parsing right or something.

Even pasting the bytes into an online msgpack converter comes up with the same result. It does pass through decodeExtension when it hits byte d7, but ..something isn't right!

![image](https://user-images.githubusercontent.com/7980490/169699146-ee311063-eabf-42ec-b925-4329ab0be92d.png)
![image](https://user-images.githubusercontent.com/7980490/169699162-7df27248-96b4-40ad-878c-da978d45845c.png)

If you paste
```93 ab 66 6c 75 65 6e 74 2e 69 6e 66 6f db 00 00 00 86 92 d7 00 62 8a 42 58 39 24 35 67 81 a7 6d 65 73 73 61 67 65 d9 70 5b 69 6e 70 75 74 5f 74 61 69 6c 5d 20 66 6f 6c 6c 6f 77 69 6e 67 20 74 61 69 6c 20 6f 66 20 2f 68 6f 6d 65 2f 66 6f 72 62 69 64 64 65 6e 65 72 61 2f 61 74 62 53 65 72 76 69 63 65 2f 6c 6f 67 73 2f 50 61 79 54 72 69 65 41 54 42 53 65 72 76 69 63 65 2d 30 2e 30 2e 32 2d 61 6c 70 68 61 2d 61 74 62 2d 30 35 2d 32 32 2d 32 32 2e 6c 6f 67 82 a4 73 69 7a 65 01 aa 63 6f 6d 70 72 65 73 73 65 64 a4 74 65 78 74```

into https://toolslick.com/conversion/data/messagepack-to-json

it shows the binary chars in the decoded message as well.. I suppose if it didn't have the right extension, this could be expected; however after d7 is 80 which decodeExtension seems to think is type -128; the only type we're adding here is 0, correct?

If you paste in the part of the message including only the actual message, the converter returns false (and indeed the first byte is false)

```c2 92 d7 80 62 c2 8a 42 58 2f c2 8f 51 c4 84 c2 a3 70 69 64 cd 88 e9 a4 b0 70 69 64 cd 88 e3 a6 b7 6f 72 6b 65 72 00 c2 a7 6d 65 73 73 61 67 65 d9 b5 73 74 61 72 74 69 6e 67 20 66 6c 75 65 6e 74 64 20 77 6f 72 6b 65 72 20 70 69 64 3d 31 38 36 36 35 20 70 70 69 64 3d 31 38 36 35 39 20 77 6f 72 6b 65 72 3d 30```

This one is really bugging me and I'm still not entirely sure if the issue is in this lib, msgpack lib, or that fluentd not following spec proper??

**Comment by jamiees2** [comment]
Dug into this today, turns out this is a UTF8 decoding issue, `@msgpack/msgpack` completely wrangles the bytes in the string when it decodes them :/

**Comment by ForbiddenEra** [comment]
> Fix released in v1.0.9

Awesome!!! Thanks so much!

Glad you were able to figure it out; A UTF8 was on my radar but not as high up as thoughts of some sort of secondary decoding issue kind of thing (ie, having to decode a msgpack message within the main message)

Will try this when I can and let you know if I run into any issues.

**Comment by ForbiddenEra** [comment]
Wait a minute; can we clarify something here?

You said:

`When data is sent in the msgpack str format, the data ends up getting deserialized as UTF8 in @msgpack/msgpack.`

Now, the msgpack spec says that the raw str format is UTF8.

At first I thought perhaps `@msgpack/msgpack` was the culprit, but if the spec says UTF8 and `@msgpack/msgpack` is decoding as UTF8, should that not be correct?

Where is it becoming NOT UTF8 (ascii?)? Is it fluentd encoding it this way, or does that somehow happen within this library?

Just - if this issue is actually rooted in another package, while I definitely appreciate your fix, it would probably be ideal long-term to notify the maintainers of the package with the core issue.

**Comment by jamiees2** [comment]
Yeah, I think the actual problem is in `msgpack-ruby`, at least `@msgpack/msgpack` seems to be doing the right thing according to the spec.

The thing is, bytes like 0x92 aren't even serializable in UTF-8, so I'm not sure how this would ever have worked. I also got wildly different results when I ran with TEXT_DECODING=force, which forces the msgpack decoder to use `TextDecoder` instead of their custom one, so it's implementation dependent. I initially looked at ways to reverse the utf8 decoding process, but it looked like it was lossy, and also seemed harder than just messing with the parsing instance.

The data was never in UTF8, fluentd was encoding it in this way. All it does is encode it in msgpack `bin` format, but stick a `0xd9/0xda/0xdb` in front instead of a `0xc4/0xc5/0xc6`. 

I'm actually somewhat confused why fluentd sends its data in this way, it says it's for backwards compatibility reasons, but fluentd accepts `bin` formatted data as well. I imagine `msgpack-ruby` had a bug in it that caused this behavior, and once it got fixed they couldn't change both at once? idk

**Comment by ForbiddenEra** [comment]
Well, your insight is much appreciated.

I did create issues on the `fluent/fluentd` tracker, I think I also did on `@msgpack/msgpack` although perhaps I should close that one and open one for the ruby version..

little bit of a weird one!
